//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Lego_Project_Core.Models
{
	/// <summary>Lego Set</summary>
	[PublishedContentModel("legoSet")]
	public partial class LegoSet : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "legoSet";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public LegoSet(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<LegoSet, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("image")]
		public IPublishedContent Image
		{
			get { return this.GetPropertyValue<IPublishedContent>("image"); }
		}

		///<summary>
		/// Set Code: Lego set code
		///</summary>
		[ImplementPropertyType("setCode")]
		public string SetCode
		{
			get { return this.GetPropertyValue<string>("setCode"); }
		}

		///<summary>
		/// Set Description: Description of the lego set
		///</summary>
		[ImplementPropertyType("setDescription")]
		public IHtmlString SetDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("setDescription"); }
		}

		///<summary>
		/// Set Title: Title of a lego set
		///</summary>
		[ImplementPropertyType("setTitle")]
		public string SetTitle
		{
			get { return this.GetPropertyValue<string>("setTitle"); }
		}
	}
}
