//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Lego_Project_Core.Models
{
	/// <summary>Local Settings</summary>
	[PublishedContentModel("localSettings")]
	public partial class LocalSettings : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "localSettings";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public LocalSettings(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<LocalSettings, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// News Teaser Length: Length of the teaser text
		///</summary>
		[ImplementPropertyType("newsTeaserLength")]
		public int NewsTeaserLength
		{
			get { return this.GetPropertyValue<int>("newsTeaserLength"); }
		}

		///<summary>
		/// News Teaser Outro: The ending of the teaser text for news
		///</summary>
		[ImplementPropertyType("newsTeaserOutro")]
		public string NewsTeaserOutro
		{
			get { return this.GetPropertyValue<string>("newsTeaserOutro"); }
		}

		///<summary>
		/// Review teaser length: Length of the review teaser
		///</summary>
		[ImplementPropertyType("reviewTeaserLength")]
		public int ReviewTeaserLength
		{
			get { return this.GetPropertyValue<int>("reviewTeaserLength"); }
		}

		///<summary>
		/// Review teaser outro: Outro for the review teaser
		///</summary>
		[ImplementPropertyType("reviewTeaserOutro")]
		public string ReviewTeaserOutro
		{
			get { return this.GetPropertyValue<string>("reviewTeaserOutro"); }
		}
	}
}
