//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Lego_Project_Core.Models
{
	/// <summary>Review</summary>
	[PublishedContentModel("review")]
	public partial class Review : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "review";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Review(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Review, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Lego  Code: The lego code of the set
		///</summary>
		[ImplementPropertyType("legoCode")]
		public string LegoCode
		{
			get { return this.GetPropertyValue<string>("legoCode"); }
		}

		///<summary>
		/// Related Set: Select a related set
		///</summary>
		[ImplementPropertyType("relatedSet")]
		public IPublishedContent RelatedSet
		{
			get { return this.GetPropertyValue<IPublishedContent>("relatedSet"); }
		}

		///<summary>
		/// Review Text: The review article itself
		///</summary>
		[ImplementPropertyType("reviewText")]
		public IHtmlString ReviewText
		{
			get { return this.GetPropertyValue<IHtmlString>("reviewText"); }
		}

		///<summary>
		/// Score: The score shown as a integer (best of 10)
		///</summary>
		[ImplementPropertyType("score")]
		public int Score
		{
			get { return this.GetPropertyValue<int>("score"); }
		}

		///<summary>
		/// Set Name: Name of the lego set
		///</summary>
		[ImplementPropertyType("setName")]
		public string SetName
		{
			get { return this.GetPropertyValue<string>("setName"); }
		}

		///<summary>
		/// Slider Images: Select images shown as a slider at the bottom
		///</summary>
		[ImplementPropertyType("sliderImages")]
		public IEnumerable<IPublishedContent> SliderImages
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("sliderImages"); }
		}
	}
}
